from .nodes.type_node import (
   AliasTypeNode, AliasLinkTypeNode, PrimitiveTypeNode, AnyTypeNode,
   ClassTypeNode, NDArrayTypeNode, NoneTypeNode, SequenceTypeNode,
   TupleTypeNode, DirectAliasTypeNode, DictTypeNode, UnionTypeNode
)
from collections import OrderedDict


_ALIASES = (
    AliasTypeNode.int("void*", "IntPointer", "Represents an arbitrary pointer"),
    AliasTypeNode.union("Mat",
                        items=(ClassTypeNode("Mat"), NDArrayTypeNode("Mat")),
                        export_name="MatLike"),
    AliasTypeNode.sequence("MatShape", PrimitiveTypeNode.int()),
    AliasTypeNode.sequence("Size", PrimitiveTypeNode.int(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Size2f", PrimitiveTypeNode.float(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Scalar", PrimitiveTypeNode.float(),
                           comment="Required length is at most 4"),
    AliasTypeNode.sequence("Point", PrimitiveTypeNode.int(),
                           comment="Required length is 2"),
    AliasLinkTypeNode("Point2i", "Point"),
    AliasTypeNode.sequence("Point2f", PrimitiveTypeNode.float(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Point2d", PrimitiveTypeNode.float(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Point3i", PrimitiveTypeNode.int(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Point3f", PrimitiveTypeNode.float(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Point3d", PrimitiveTypeNode.float(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Range", PrimitiveTypeNode.int(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Rect", PrimitiveTypeNode.int(),
                           comment="Required length is 4"),
    AliasTypeNode.sequence("Rect2i", PrimitiveTypeNode.int(),
                           comment="Required length is 4"),
    AliasTypeNode.sequence("Rect2d", PrimitiveTypeNode.float(),
                           comment="Required length is 4"),
    AliasTypeNode.tuple("RotatedRect",
                        items=(AliasLinkTypeNode("Point2f"),
                               AliasLinkTypeNode("Size"),
                               PrimitiveTypeNode.float()),
                        comment="Any type providing sequence protocol is supported"),
    AliasTypeNode.tuple("TermCriteria",
                        items=(
                            ClassTypeNode("TermCriteria.Type"),
                            PrimitiveTypeNode.int(),
                            PrimitiveTypeNode.float()),
                        comment="Any type providing sequence protocol is supported"),
    AliasTypeNode.sequence("Vec2i", PrimitiveTypeNode.int(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Vec2f", PrimitiveTypeNode.float(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Vec2d", PrimitiveTypeNode.float(),
                           comment="Required length is 2"),
    AliasTypeNode.sequence("Vec3i", PrimitiveTypeNode.int(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Vec3f", PrimitiveTypeNode.float(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Vec3d", PrimitiveTypeNode.float(),
                           comment="Required length is 3"),
    AliasTypeNode.sequence("Vec4i", PrimitiveTypeNode.int(),
                           comment="Required length is 4"),
    AliasTypeNode.sequence("Vec4f", PrimitiveTypeNode.float(),
                           comment="Required length is 4"),
    AliasTypeNode.sequence("Vec4d", PrimitiveTypeNode.float(),
                           comment="Required length is 4"),
    AliasTypeNode.sequence("Vec6f", PrimitiveTypeNode.float(),
                           comment="Required length is 6"),
    AliasTypeNode.class_("FeatureDetector", "Feature2D"),
    AliasTypeNode.class_("FeatureExtractor", "Feature2D"),
    AliasTypeNode.union("GProtoArg",
                        items=(ClassTypeNode("GScalar"),
                               ClassTypeNode("GMat"),
                               ClassTypeNode("GOpaqueT"),
                               ClassTypeNode("GArrayT"))),
    SequenceTypeNode("GProtoArgs", AliasLinkTypeNode("GProtoArg")),
    AliasTypeNode.sequence("GProtoInputArgs", AliasLinkTypeNode("GProtoArg")),
    AliasTypeNode.sequence("GProtoOutputArgs", AliasLinkTypeNode("GProtoArg")),
    AliasTypeNode.union("GOptRunArg",
                        items=(AliasLinkTypeNode("MatLike"),
                               AliasLinkTypeNode("Scalar"),
                               ClassTypeNode("GOpaqueT"),
                               ClassTypeNode("GArrayT"),
                               SequenceTypeNode("GOptRunArg", AnyTypeNode("GOptRunArg")),
                               NoneTypeNode)),
    AliasTypeNode.union("Prim",
                        items=(ClassTypeNode("gapi.wip.draw.Text"),
                               ClassTypeNode("gapi.wip.draw.Circle"),
                               ClassTypeNode("gapi.wip.draw.Image"),
                               ClassTypeNode("gapi.wip.draw.Line"),
                               ClassTypeNode("gapi.wip.draw.Rect"),
                               ClassTypeNode("gapi.wip.draw.Mosaic"),
                               ClassTypeNode("gapi.wip.draw.Poly"))),
    SequenceTypeNode("Prims", AliasLinkTypeNode("Prim")),
    AliasTypeNode.array("Mat33f", (3, 3), "float"),
    AliasTypeNode.array("Mat33d", (3, 3), "numpy.float64"),
    AliasTypeNode.array("Mat44f", (4, 4), "float"),
    AliasTypeNode.array("Mat44d", (4, 4), "numpy.float64"),
    PrimitiveTypeNode.string("char"),
    PrimitiveTypeNode.int("uchar"),
    PrimitiveTypeNode.int("unsigned"),
    PrimitiveTypeNode.string("String"),
    PrimitiveTypeNode.string(),
    PrimitiveTypeNode.string("c_string"),
    PrimitiveTypeNode.float("double"),
    PrimitiveTypeNode.int("int64"),
    PrimitiveTypeNode.int("size_t"),
    NoneTypeNode("void"),
    NDArrayTypeNode("vector<uchar>", dtype="numpy.uint8"),
    NDArrayTypeNode("vector_uchar", dtype="numpy.uint8"),
    TupleTypeNode("GMat2", items=(ClassTypeNode("GMat"),
                                  ClassTypeNode("GMat"))),
    ClassTypeNode("GOpaque", "GOpaqueT"),
    ClassTypeNode("GArray", "GArrayT"),
    SequenceTypeNode("GCompileArgs", ClassTypeNode("GCompileArg")),
    SequenceTypeNode("GTypesInfo", ClassTypeNode("GTypeInfo")),
    SequenceTypeNode("GRunArgs", ClassTypeNode("GRunArg")),
    SequenceTypeNode("GMetaArgs", ClassTypeNode("GMetaArg")),
    AliasTypeNode.callable(
        "detail_ExtractArgsCallback",
        argument_type=SequenceTypeNode("GTypesInfo", ClassTypeNode("GTypeInfo")),
        return_type=SequenceTypeNode("GRunArgs", ClassTypeNode("GRunArg")),
        export_name="ExtractArgsCallback"
    ),
    AliasTypeNode.callable(
        "detail_ExtractMetaCallback",
        argument_type=SequenceTypeNode("GTypesInfo", ClassTypeNode("GTypeInfo")),
        return_type=SequenceTypeNode("GMetaArgs", ClassTypeNode("GMetaArg")),
        export_name="ExtractMetaCallback"
    ),
    DirectAliasTypeNode("LayerId", ClassTypeNode("DictValue")),
    PrimitiveTypeNode.int("cvflann_flann_distance_t"),
    PrimitiveTypeNode.int("flann_flann_distance_t"),
    PrimitiveTypeNode.int("cvflann_flann_algorithm_t"),
    PrimitiveTypeNode.int("flann_flann_algorithm_t"),
    DictTypeNode("flann_IndexParams",
                 key_type=PrimitiveTypeNode.string(),
                 value_type=UnionTypeNode("flann_IndexParams::value", items=(
                     PrimitiveTypeNode.bool(),
                     PrimitiveTypeNode.int(),
                     PrimitiveTypeNode.float(),
                     PrimitiveTypeNode.string())
                 )),
    DictTypeNode("flann_SearchParams",
                 key_type=PrimitiveTypeNode.string(),
                 value_type=UnionTypeNode("flann_IndexParams::value", items=(
                     PrimitiveTypeNode.bool(),
                     PrimitiveTypeNode.int(),
                     PrimitiveTypeNode.float(),
                     PrimitiveTypeNode.string())
                 )),
)

ALIASES = OrderedDict(zip((alias.ctype_name for alias in _ALIASES), _ALIASES))
