from typing import NamedTuple, Union, Sequence, Optional
from collections import OrderedDict


class CTypeAlias(NamedTuple):
    typename: str
    py_type: str
    dependency_imports: Union[str, Sequence[str]] = ()
    alias: Optional[str] = None
    comment: str = ""

    @property
    def export_name(self) -> str:
        if self.alias is None:
            return self.typename
        return self.alias


_ALIASES = (
    CTypeAlias("void*", alias="IntPointer",
               py_type="int",
               comment="Represents an arbitrary pointer"),
    CTypeAlias("Mat", alias="MatLike",
               py_type="np.ndarray[Any, np.dtype=[np.generic]] | Mat",
               dependency_imports=("import numpy as np",
                                   "from typing import Any",
                                   "from cv2.mat_wrapper import Mat")),
    CTypeAlias("MatShape", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence"),
    CTypeAlias("Size", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Size2f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Scalar", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Point", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Point2i", py_type="Point"),
    CTypeAlias("Point2f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Point2d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Point3i", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Point3f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Point3d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Range", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Rect", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Rect2i", py_type="Rect"),
    CTypeAlias("Rect2d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Rect2d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("RotatedRect", py_type="tuple[Point2f, Size, float]",
               comment="Any type providing sequence protocol is supported"),
    CTypeAlias("TermCriteria", py_type="tuple[TermCriteria_Type, int, float]",
               comment="Any type providing sequence protocol is supported"),
    CTypeAlias("Vec2i", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Vec2f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Vec2d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 2"),
    CTypeAlias("Vec3i", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Vec3f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Vec3d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 3"),
    CTypeAlias("Vec4i", py_type="Sequence[int]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Vec4f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Vec4d", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 4"),
    CTypeAlias("Vec6f", py_type="Sequence[float]",
               dependency_imports="from typing import Sequence",
               comment="Required length is 6"),
    CTypeAlias("FeatureDetector", py_type="Feature2D"),
    CTypeAlias("FeatureExtractor", py_type="Feature2D"),
    CTypeAlias("GProtoArg", py_type="GScalar | GMat | GOpaqueT | GArrayT"),
    CTypeAlias("GProtoInputArgs", py_type="Sequence[GProtoArgs]",
               dependency_imports="from typing import Sequence"),
    CTypeAlias("GProtoOutputArgs", py_type="Sequence[GProtoArgs]",
               dependency_imports="from typing import Sequence"),
    CTypeAlias("GOptRunArg", py_type="MatLike | Scalar | GOpaqueT | Sequence[Any] | None",
               dependency_imports="from typing import Sequence"),
    CTypeAlias("Prim",
               py_type="gapi_wip_draw_Text | gapi_wip_draw_Circle"
               " | gapi_wip_draw_Image | gapi_wip_draw_Line | gapi_wip_draw_Rect"
               " | gapi_wip_draw_Mosaic | gapi_wip_draw_Poly"),
    CTypeAlias("Mat33f",
               py_type="np.ndarray[(3, 3), np.dtype=[float]]",
               dependency_imports="import numpy as np"),
    CTypeAlias("Mat33d",
               py_type="np.ndarray[(3, 3), np.dtype=[np.float64]]",
               dependency_imports="import numpy as np"),
    CTypeAlias("Mat44f",
               py_type="np.ndarray[(4, 4), np.dtype=[float]]",
               dependency_imports="import numpy as np"),
    CTypeAlias("Mat44d",
               py_type="np.ndarray[(4, 4), np.dtype=[np.float64]]",
               dependency_imports="import numpy as np"),
)

ALIASES = OrderedDict(zip((alias.typename for alias in _ALIASES), _ALIASES))
